require "config.nvimtree"
require "config.lspconfig"
require "config.cmp"
require "config.lsp-signature"
require "config.treesitter"
require "config.bufferline"
require "config.lualine"
require "config.autopairs"
require "config.gitsigns"
--require "config.indent_blankline"
require "config.neosolarized"
require "config.telescope"
require "config.todo-comments"
require "config.undotree"
require "config.formatter"


